Importing Libraries
Numpy for matrics calculation
Pandas to read file
tensorflow to build neural network

In [31]:
import numpy as np
import pandas as pd
import tensorflow as tf

Importing dataset and giving values of x to read as index number and is not much use in predicting the result so starting from third column

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


Encoding categorical data which have relation between them like male or female

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [6]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding for data which don't have relation between them such as name of a country

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Spliting dataset to train and testing set eith test set of size 0.2 or 20% of total set.

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

Feature Scaling data / Normalization of data

In [13]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
ann = tf.keras.models.Sequential()

First Layer of neural network with 6 neurons and activation function Relu

In [20]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

Second hidden Layer of neural network with 6 neurons and activation function Relu

In [21]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

Output layer of neural network

In [22]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

Using adam optimizer as it automatically alter the value of connection weights and loss binary_crossentropy for binary problem for non-binary problem use categorical crossentropy loss

In [24]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

Training Neural Network

In [ ]:
ann.fit(x_train,y_train,batch_size = 32, epochs = 100 )

Predicting the result with data in 2-D array if it is greater than 0.5 answer would be true

In [27]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 56ms/step
[[False]]


Predicting the test result

In [28]:
y_pred = ann.predict(x_test)
y_pred = y_pred>0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1518   77]
 [ 198  207]]


0.8625